# Generated by Django 2.2.14 on 2020-07-26 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('PostingID', models.AutoField(primary_key=True, serialize=False)),
                ('StreetAddress', models.CharField(max_length=255)),
                ('NumberOfBedrooms', models.IntegerField()),
                ('NumberOfBathrooms', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('GenderPreference', models.IntegerField()),
                ('PetsAllowed', models.IntegerField()),
                ('ParkingIncluded', models.IntegerField()),
                ('WasherDryerIncluded', models.IntegerField()),
                ('UtilitiesIncluded', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
