# Generated by Django 2.2.14 on 2020-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='GenderPreference',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('none', 'none')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='ParkingIncluded',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Fee', 'Fee'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='PetsAllowed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Fee', 'Fee'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='UtilitiesIncluded',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Partial', 'Partial'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='WasherDryerIncluded',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Fee', 'Fee'), ('No', 'No')], max_length=20),
        ),
    ]
